export default types = {
    ADD_LIST_TOP_POPULARITY: 'ADD_LIST_TOP_POPULARITY',
    SEND_ID_MOVIE: 'SEND_ID_MOVIE',
    SEND_CURRENT_USER: 'SEND_CURRENT_USER',
    CLEAR_CURRENT_USER: 'CLEAR_CURRENT_USER',
    SEND_ROOT_NAVIGATION: 'SEND_ROOT_NAVIGATION',
    SEND_LIST_RECENTS: 'SEND_LIST_RECENTS',
    SEND_LIST_FAVORITES: 'SEND_LIST_FAVORITES',
    SEND_LIST_WATCH_LATER: 'SEND_LIST_WATCH_LATER'
}